### ISSUE TITLE
MySQLPlugin now causing duplicate entries in DB

### ISSUE THREAD

**Issue by tupolov** [firefly2442/Arma2NETMySQLPlugin#1]
Using the latest plugin that fixed the printing in the log, we now see duplicate entries in the DB. This is occuring on every insert on the DB.

We only see a single insert call in the mysqlplugin log, but duplicate entries in the DB.

Evidence here on an inserting a mission and returning mission data

Info: 10:05:07 - Arma2NETMySQL Plugin Started.
Info: 10:05:07 - Version number: 0.1
Info: 10:05:07 - Compiled with Arma2NET Version: 1.10.0.0
Info: 10:05:07 - Loading databases...
Info: 10:05:07 - Database: arma IPAddress: 127.0.0.1 Port: 3306 Username: arma Password: NotShownForSecurityReasons
Info: 10:05:07 - Received - Database: arma Procedure: GetMissionByName Parameters: tna=32_A2CO_COOP_BAF_USA_vs_TAK_INS_GUE_4-44
Info: 10:05:07 - Parsing parameters...
Info: 10:05:07 - Returning to Arma2: 
Info: 10:05:07 - Parsing parameters...
Info: 10:05:07 - Received - Database: arma Procedure: NewMission Parameters: tna=32_A2CO_COOP_BAF_USA_vs_TAK_INS_GUE_4-44,ttd=1,tsc=1,tgsc=1,tlog=1,twea=1,tace=1,tlv=1,tobj=1
Info: 10:05:07 - Parsing parameters...
Info: 10:05:07 - Returning to Arma2: 
Info: 10:05:07 - Parsing parameters...
Info: 10:05:08 - Received - Database: arma Procedure: GetMissionByName Parameters: tna=32_A2CO_COOP_BAF_USA_vs_TAK_INS_GUE_4-44
Info: 10:05:08 - Parsing parameters...
Info: 10:05:08 - Returning to Arma2: 83,32_A2CO_COOP_BAF_USA_vs_TAK_INS_GUE_4-44,1,,1,1,1,1,1,1,1,0,0,0,0,0,82,32_A2CO_COOP_BAF_USA_vs_TAK_INS_GUE_4-44,1,,1,1,1,1,1,1,1,0,0,0,0,0,

Note: the duplicate entry returned in the last log entry

Tested with MySQL Connector 6.5.4 and 6.4.5

**Comment by firefly2442** [comment]
Should be fixed now.  Still not sure why the code that printed out the IEnumerable array made the procedure run twice but eh, it's fixed.  :)

See commit hash: 1bb15cf215c1ca37b8889ef28b9297d1da7bad4c

**Comment by tupolov** [comment]
Awesome thanks!

On Sat, Jun 23, 2012 at 12:31 AM, Patrick <
reply@reply.github.com
