### ISSUE TITLE
Test on Windows Server 2012

### ISSUE THREAD

**Issue by firefly2442** [firefly2442/Arma2NETMySQLPlugin#27]
According to a user, the plugin works on Windows Server 2008, however, it does not work on Windows Server 2012.  I'm guessing this has something to do with using a compiled version of the plugin and the version of the .NET framework installed.  I don't have a Windows Server 2012 instance to test this on so if anyone else can test it, that would be great.

**Comment by Raz89x** [comment]
Hosted an A3 Life server on Windows Server r2 standard, had no issues what so ever other than it would crash out with an exception after having it run for more than 2 days without restarting arma
