### ISSUE TITLE
Spelling - Logger.cs

### ISSUE THREAD

**Issue by Raz89x** [firefly2442/Arma2NETMySQLPlugin#28]
public static void Stop()
        {
            if (State == loggerState.Started)
            {
                try
                {
                    sw.Flush();
                    sw.Close();
                    fs.Close();
                    state = loggerState.Stopped;
                }
                catch (Exception ex)
                {
                    Console.WriteLine("EXCEPTION: An exception occured while stopping the logger.\n**\t{0}", ex.ToString());
                }
            }
        }

occured (occurred) is misspelled

**Comment by firefly2442** [comment]
Thank you!
