### ISSUE TITLE
Plug in doesn't load in certain circumstances

### ISSUE THREAD

**Issue by tupolov** [firefly2442/Arma2NETMySQLPlugin#5]
From the logs

10/17/2012 05:10:37 Log: Unmanaged side loaded
10/17/2012 05:10:37 Info Arma2NET 2.2.0.0 running on CLR 4.0.30319.17929
10/17/2012 05:10:37 Info Loaded into process arma2oaserver
10/17/2012 05:10:37 Info Loading addins
10/17/2012 05:10:37 Error Failed to create addin application domain Arma2NETMySQLPlugin for F:\Program Files (x86)\Bohemia Interactive\ArmA 2\@Arma2NET\AddIns\Arma2NETMySQLPlugin\Arma2NETMySQLPlugin.dll
10/17/2012 05:10:37 Warn Falling back to the main application domain

Spoke to Scott W, suggested we remove Utils.FileVersion from the logging call in Startup.Connection (startup.cs). I have recompiled with this change and have asked the person with the issue to test. Will let you know if it works.... 

Great work btw... thanks for the updates.

**Comment by tupolov** [comment]
Just to let you know that change fixed the persons issues. Suggest making the change to your code

**Comment by firefly2442** [comment]
Thank you.  Closing issue.
